#!/usr/bin/env R
#Title: PCA Plotting for Bulk RNAseq
#Version: 0.1
#Date: 2018-04-18
#Author: Kishore R.Anekalla 
# Rohan Verma


#may have issues with LAPACK so just installing Xcode libraries for mac is fine!

# useful packages 
# source("https://bioconductor.org/biocLite.R")
# pkgs<-c("biomaRt","GenomicRanges","BiocParallel","heatmap3","genefilter","dplyr",
#         "DESeq2","edgeR","Hmisc","ggplot2","readxl","Cairo","pheatmap","ggplot2",
#         "gplots","calibrate","stringi","PoiClaClu","ggrepel","RColorBrewer")
# for(i in 1:length(pkgs)){
#   library(pkgs[i],character.only = TRUE)
# }

# pca plot using rlog-transformed values
getpca_rlog<-function(x,y,outputname,cols='auto'){
  "
    x <- counts file cleaned
    y <- groups file cleaned and preferably ordered (same as cols in counts)
    outputname <- output directory location
    cols = colors to be used for groups auto default
  "
  packages.needed <- c('DESeq2','ggplot2','PoiClaClu','RColorBrewer','pheatmap')
  lapply(packages.needed, require, character.only = TRUE)
  
 ####order groups file and check if sample names are the same####
  if(sum(colnames(x) %in%  y$samples)<nrow(y)){stop("sample names in groups and counts do not match")}
  
  if(sum(colnames(x) == y$samples)<nrow(y)){
    pos <- c()
    for (i in colnames(x)){pos=c(pos,grep(i,y$samples))}
    y <- y[pos,]
  }
  
  #### get colors and set up dir ####
  cols=cols
  numunique=length(unique(groups$condition)) 
  if (cols =='auto'){
    hues = seq(15, 375, length = numunique + 1)
    cols=hcl(h = hues, l = 65, c = 100)[1:numunique]
    names(cols) = unique(groups$condition)
  }
  
  if (length(cols) != numunique){stop(paste0('incorrect number of colors specified need ',numunique,' have ',length(cols)))}
  
  #ensure directory exists if not then create one
  if (file.exists(outputname)==F){
    dir.create(file.path(outputname))
  }
  #### normcounts and scree plot ####
  normfile <- paste(outputname,"/","_rlognorm.txt", sep="")
  scree_plot_file_name <- paste(outputname,"/","_scree_plot.pdf", sep="")
  scree_plot_name <- paste("Scree plot for ", outputname, sep="")
  ddsMat <- DESeqDataSetFromMatrix(countData = x, colData = y, design =~condition) # condition can be generated by mixing the factors /coldata apparoach
  print("# of ensembl IDS in the unfiltered dataset")
  print(nrow(ddsMat))
  # filtering the set
  dds <- ddsMat[ rowSums(counts(ddsMat)) > ceiling(nrow(groups)/2), ] # filtering
  print("# of Ensembl Ids post filtering")
  print(nrow(dds))
  rld <- rlog(dds, blind=TRUE)
  write.table(assay(rld),file=normfile,sep="\t")
  print(head(assay(rld), 3))
  ntop=1000
  Pvars <- rowVars(assay(rld))
  select <- order(Pvars, decreasing = TRUE)[seq_len(min(ntop, length(Pvars)))]
  PCA <- prcomp(t(assay(rld)[select, ]), scale = T)
  head(PCA)
  #Scree plot
  scree_plot_file_name <- paste(outputname,"/","_Scree.pdf", sep="")
  cairo_pdf(filename = scree_plot_file_name,
            bg = "white")
  pct.var <- (PCA$sdev^2/ sum(PCA$sdev^2))*100
  PC <- c(1:length(pct.var))
  pcvarexp <- data.frame(PC,pct.var)[1:10,]
  scrplot <- ggplot(pcvarexp,aes(x=PC,y=pct.var))+geom_point()+
    scale_x_continuous(breaks = c(1:10))+ theme_light()+
    ggtitle('Scree plot')
  print(scrplot)
  dev.off()
  
  #### distance matrix plot ####

  poisd <- PoissonDistance(t(counts(dds)))
  samplePoisDistMatrix <- as.matrix( poisd$dd )
  rownames(samplePoisDistMatrix) <- paste( rld$samples)
  colnames(samplePoisDistMatrix) <- NULL
  head(samplePoisDistMatrix)
  dist_plot_file_name <- paste(outputname,"/","_distance_plot.pdf", sep="")
  cairo_pdf(as.character(dist_plot_file_name),bg = "white")
  hmcol<-brewer.pal(11,"RdBu")
  pheatmap(samplePoisDistMatrix,clustering_distance_rows=poisd$dd,clustering_distance_cols=poisd$dd,
           col=hmcol,main="distance matrix (poissons) plot")
  dev.off()
  #### PCA Plots ####
  percentVar <- round(100*PCA$sdev^2/sum(PCA$sdev^2),1)
  print(colData(rld)$condition)
  pcadata = data.frame(PC1 = PCA$x[,1],
                       PC2 = PCA$x[,2],
                       PC3 = PCA$x[,3],
                       PC4 = PCA$x[,4],
                       condition = colData(rld)$condition) # sampleNumber = colData(rld)$sampleNumber , or , colortemp = y$colors,# may try
  print(pcadata)
  #1st vs 2nd
  pca_plot_file_name <- paste(outputname,"/","_PC1vPC2_plot.pdf", sep="")
  cairo_pdf(filename = pca_plot_file_name,
            bg = "white")
  p1<-ggplot(pcadata, aes(PC1, PC2, color=condition,label = row.names(pcadata))) + geom_point(size=10) +
    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  p1<-p1+ scale_color_manual(values=cols)
  print(p1) 
  dev.off()
  #labeled 1v2
  pca_plot_file_name <- paste(outputname,"/","_PC1vPC2_plot_labeled.pdf", sep="")
  cairo_pdf(filename = pca_plot_file_name,
            bg = "white")
  p1<-ggplot(pcadata, aes(PC1, PC2, color=condition,label = row.names(pcadata))) + geom_point(size=5) +
    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  p1<-p1+ scale_color_manual(values=cols)
  p1<-p1 + geom_label(size=3)
  print(p1) # can be renamed to pc1_2
  dev.off()
  #2nd Vs 3rd
  pca_plot_file_name <- paste(outputname,"/","_PC2vPC3_plot.pdf", sep="")
  cairo_pdf(filename = pca_plot_file_name , bg = "white")
  p2<-ggplot(pcadata, aes(PC2, PC3, color=condition,label = row.names(pcadata))) + geom_point(size=10) +
    xlab(paste0("PC2: ",percentVar[2],"% variance")) +
    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  p2<-p2+ scale_color_manual(values=cols)
  print(p2)
  dev.off()
  #labeled version 2v3
  pca_plot_file_name <- paste(outputname,"/","_PC2vPC3_plot_labeled.pdf", sep="")
  cairo_pdf(filename = pca_plot_file_name , bg = "white")
  p2<-ggplot(pcadata, aes(PC2, PC3, color=condition,label = row.names(pcadata))) + geom_point(size=5) +
    xlab(paste0("PC2: ",percentVar[2],"% variance")) +
    ylab(paste0("PC3: ",percentVar[3],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  p2<-p2+ scale_color_manual(values=cols)
  p2<-p2+geom_label(size=3)
  print(p2)
  dev.off()
  #3rd vs 4th
  pca_plot_file_name <- paste(outputname,"/","_PC3vPC4_plot.pdf", sep="")
  cairo_pdf(filename =pca_plot_file_name, bg = "white")
  p3<-ggplot(pcadata, aes(PC3, PC4, color=condition,label = row.names(pcadata))) + geom_point(size=10) +
    xlab(paste0("PC3: ",percentVar[3],"% variance")) +
    ylab(paste0("PC4: ",percentVar[4],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  #p + geom_text(size=2)
  p3<-p3+ scale_color_manual(values=cols)
  print(p3)
  dev.off()
  #labeled version 3v4
  pca_plot_file_name <- paste(outputname,"/","_PC3vPC4_plot_labeled.pdf", sep="")
  cairo_pdf(filename =pca_plot_file_name, bg = "white")
  p3<-ggplot(pcadata, aes(PC3, PC4, color=condition,label = row.names(pcadata))) + geom_point(size=5) +
    xlab(paste0("PC3: ",percentVar[3],"% variance")) +
    ylab(paste0("PC4: ",percentVar[4],"% variance")) +
    theme(aspect.ratio = 1) +
    theme(panel.background = element_rect(fill = "white"), panel.border = element_rect(fill=NA, color="black"))+
    theme(legend.key = element_rect(fill = "white"))+
    coord_fixed()
  p3<-p3+ scale_color_manual(values=cols)
  p3<-p3+geom_label(size=3)
  print(p3)
  dev.off()
}

#source this script and use to run


